-- 코드를 입력하세요
SELECT A.ANIMAL_ID,A.NAME from ANIMAL_INS A,ANIMAL_OUTS B
where TO_CHAR(B.DATETIME - A.DATETIME) > 0
and A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY TO_NUMBER(TO_CHAR(B.DATETIME - A.DATETIME)) DESC
FETCH FIRST 2 ROW ONLY