-- 코드를 입력하세요
SELECT a.ANIMAL_ID,a.ANIMAL_TYPE,a.NAME
FROM ANIMAL_INS a ,ANIMAL_OUTS  b
WHERE a.ANIMAL_ID = b.ANIMAL_ID
AND a.SEX_UPON_INTAKE != b.SEX_UPON_OUTCOME
-- AND a.SEX_UPON_INTAKE NOT LIKE 'Intact%'
-- AND b.SEX_UPON_OUTCOME LIKE 'Spayed%'
-- OR b.SEX_UPON_OUTCOME LIKE 'Neutered%'