-- 코드를 입력하세요
SELECT a.PRODUCT_ID,a.PRODUCT_NAME
    ,sum((Price*AMOUNT))TOTAL_SALES
FROM FOOD_PRODUCT a,FOOD_ORDER  b
WHERE a.PRODUCT_ID = b.PRODUCT_ID
AND to_char(PRODUCE_DATE,'YYYYMM') =202205
group by a.PRODUCT_ID,a.PRODUCT_NAME
order by TOTAL_SALES desc,a.PRODUCT_ID