-- 코드를 작성해주세요
SELECT sum(SCORE) SCORE,b.EMP_NO,EMP_NAME,POSITION,EMAIL
FROM HR_DEPARTMENT a, HR_EMPLOYEES b, HR_GRADE c
WHERE a.DEPT_ID = b.DEPT_ID
AND b.EMP_NO = c.EMP_NO
AND c.YEAR ='2022'
GROUP BY b.EMP_NO,EMP_NAME,POSITION,EMAIL
ORDER BY 1 desc
LIMIT 1