-- 코드를 입력하세요
SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, DECODE(STATUS,'DONE','거래완료','SALE','판매중','예약중')STATUS
FROM USED_GOODS_BOARD
WHERE to_char(CREATED_DATE,'YYYY-MM-DD') = '2022-10-05'
ORDER BY BOARD_ID dESC